options:
  logging: CLOUD_LOGGING_ONLY  # Add this line
  serviceAccount: 'cloud-build-sa@weatherapp-453916.iam.gserviceaccount.com'  # Replace with your service account email

steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    id: 'Install dependencies'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Build the Angular project
  - name: 'node:18'
    id: 'Build Angular project'
    entrypoint: 'npm'
    args: ['run', 'build', '--', '--configuration', 'production']

  # Step 3: Deploy to Google Cloud Storage (GCS)
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Deploy to GCS'
    args: ['-m', 'rsync', '-r', '-c', '-d', 'dist/weather-dashboard/browser', 'gs://weather-dashboard-bucket']